# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AU-SEC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AU-SEC
  pod 'SwiftyJSON'
end

target 'NotificationService' do
  use_frameworks!

end
